feat: crontab target

diff --git a/Makefile.in b/Makefile.in
--- a/Makefile.in
+++ b/Makefile.in
@@ -43,6 +43,7 @@ srcdir_abs						= $(srcdir_top_abs)/src
 # gnu prefix directories
 prefix								= IN_PREFIX
 exec_prefix						= IN_EXEC_PREFIX
+bindir								= IN_BINDIR
 sbindir								= IN_SBINDIR
 libexecdir						= IN_LIBEXECDIR
 datarootdir						= IN_DATAROOTDIR
@@ -93,8 +94,18 @@ release								= $(srcdir_top)/scripts/release.sh
 ##################################################
 # Important files
 ##################################################
-configfile=$(srcdir_top)/configure
-releasefile=$(srcdir_top)/RELEASE
+configfile	 = $(srcdir_top)/configure
+releasefile	 = $(srcdir_top)/RELEASE
+
+# Options
+PROXY_HOSTNAME				 = IN_PROXY_HOSTNAME
+PROXY_PORT						 = IN_PROXY_PORT
+PROXY_HOSTSFILE				 = IN_PROXY_HOSTSFILE
+PROXY_LOGIN_USERNAME	 = IN_PROXY_LOGIN_USERNAME
+PUSHIP_CRON_LOGFILE		 = IN_PUSHIP_CRON_LOGFILE
+PUSHIP_CRON_RUNTIME		 = IN_PUSHIP_CRON_RUNTIME
+AUTOBAK_CRON_LOGFILE	 = IN_AUTOBAK_CRON_LOGFILE
+AUTOBAK_CRON_RUNTIME	 = IN_AUTOBAK_CRON_RUNTIME
 
 ##################################################
 # Default target
@@ -104,7 +115,58 @@ all: build
 ##################################################
 # Build
 ##################################################
-build:
+build: crontab
+
+define TEMPLATE_MSG
+# This file has been automatically generated by Make.
+#
+# Contained within are 4 cron job scheduling example configurations
+# for the programs:
+#
+#   - autobak
+#   - puship
+#
+# The user is expected to either copy verbatim an example
+# configuration to a cron config file or use crontab -e
+#
+# A scheduled job is represented by a line in one of the many config
+# files read by cron.
+#
+# 2 of which are:
+#
+#   - /etc/crontab
+#      minute hour day-of-month month day-of-week USER COMMAND
+#   - /var/spool/cron/<user> (through crontab -e)
+#      minute hour day-of-month month day-of-week COMMAND
+#
+# A job scheduling configuration intended for /etc/crontab cannot be
+# shared verbatim to crontab -e because of the existence of the extra
+# USER field.
+endef
+
+define PUSHIP_CRON_CONFIG
+# puship config -> /etc/crontab
+$(PUSHIP_CRON_RUNTIME) root $(bindir)/puship >> $(PUSHIP_CRON_LOGFILE) 2>&1
+
+# puship config -> crontab -e
+$(PUSHIP_CRON_RUNTIME) $(bindir)/puship >> $(PUSHIP_CRON_LOGFILE) 2>&1
+endef
+
+define AUTOBAK_CRON_CONFIG
+# autobak config -> /etc/crontab
+$(AUTOBAK_CRON_RUNTIME) root $(bindir)/autobak >> $(AUTOBAK_CRON_LOGFILE) 2>&1
+
+# autobak config -> crontab -e
+$(AUTOBAK_CRON_RUNTIME) $(bindir)/autobak >> $(AUTOBAK_CRON_LOGFILE) 2>&1
+endef
+
+
+crontab: $(srcdir)/crontab.conf
+	$(m4) -DTEMPLATE_MSG="$${TEMPLATE_MSG}" \
+	-DPUSHIP_CRON_CONFIG="$${PUSHIP_CRON_CONFIG}" \
+	-DAUTOBAK_CRON_CONFIG="$${AUTOBAK_CRON_CONFIG}" \
+	$< > $@
+	$(chmod) --verbose 644 $@
 
 ##################################################
 # Release
@@ -144,6 +206,10 @@ update:
 ##################################################
 clean:
 	-rm -f *.tar.gz
+	-rm -f $(program_name)
+	-rm -f edihosts
+	-rm -f puship
+	-rm -f crontab
 
 ##################################################
 # distclean
@@ -152,15 +218,13 @@ distclean: clean
 	-rm -f *.log
 	-rm -f .#*
 	-rm -f config.*
+	-rm -f Makefile
 
 ##################################################
 # misc
 ##################################################
 .DEFAULT:
-	@if [ ! -f "$<" ]; then
-	echo "Missing file $${file:-}"
-	exit 1
-	fi
+	@if [ ! -f "$<" ]; then echo "Missing file -> $${file:-$<}"; exit 1; fi
 
 ##################################################
 # directories
